### ISSUE TITLE
Error in sendSingleSms call with PHP 7.2

### ISSUE THREAD

**Issue by rogerguasch** [SMSEdge/API-PHP#1]
Code:
```
$send_single_sms_array = [
   'from' => 'DUMMY_TEXT',
   'to' => 34123456789, //put you phone here
   'text' => 'dummy text'
];
$this->smsClient->sendSingleSms($send_single_sms_array)
```

Error screenshot:
![image](https://user-images.githubusercontent.com/6397664/70808665-73167780-1dc0-11ea-89d4-ff910106d3c7.png)

The problem is line 140 of Validation.php

more info here: https://www.php.net/manual/en/migration70.incompatible.php#migration70.incompatible.variable-handling.indirect

**Comment by SMSEdge** [comment]
Hi, thanks for the callback.
this issue is fixed now just update your package with:
`$ composer update`
